using GeekBrains_CSharpBasics_Ln7_Tsk2.Model;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace GeekBrains_CSharpBasics_Ln7_Tsk2
{
    public partial class ComputerForm : Form
    {
        UserForm userForm = new UserForm();
        GameLogic gameData;
        public ComputerForm()
        {
            InitializeComponent();
            Setup();
        }
        void Setup()
        {
            lblGameName.Text = "The Guessing Game";
            tbRiddleText.Text = string.Concat(
                "The Guessing Game lets the user to guess a number from 1 to 100, ",
                "randomly generated by the program.", Environment.NewLine,
                "To do this, the user is given a limited number of attempts, ",
                "about which he will be informed.", Environment.NewLine,
                "In the case when the player guesses the number or ",
                "the number of attempts ends, the program reports the result ",
                "and offers to play again.");
        }

        private void btnStart_Click(object sender, EventArgs e)
        {
            btnStart.Enabled = false;
            StartGame(gameData);
            userForm.GetLinkToGameData(gameData);
            userForm.ShowDialog();
        }
        void StartGame(GameLogic data)
        {
            gameData = new GameLogic((1, 100), 7);
            lblGameName.Text = "The Pirate's Joe Riddle";
            tbRiddleText.Text = gameData.Reaction;
            gameData.updateUI += UpdateUI;
            gameData.updateUI += CheckForEndGame;
        }
        void UpdateUI() => tbRiddleText.Text = gameData.Reaction;
        void CheckForEndGame()
        {
            if (gameData.Status!=GameStatus.InProcess)
            {
                userForm.Close();
                btnStart.Text = "Restart";
                btnStart.Enabled = true;
            }
        }
    }
}
